version: '3.8'

services:
  postgresdb:
    image: postgres:16-alpine
    container_name: task-racer-postgres
    environment:
      POSTGRES_DB: task_racer
      POSTGRES_USER: task_racer
      POSTGRES_PASSWORD: task_racer
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
