spring.application.name=task-racer
# Database URL, Username, and Password
spring.datasource.url=jdbc:postgresql://localhost:5432/task_racer
spring.datasource.username=task_racer
spring.datasource.password=task_racer
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration/postgresql